export { default as AuthWidget } from './AuthWidget.vue'
export { default as Button } from './Button.vue'
export { default as Icon } from './Icon.vue'
export { default as LocaleSelector } from './LocaleSelector.vue'
export { default as Logo } from './Logo.vue'
